ZSH_CUSTOM=$HOME/.config/oh-my-zsh

CASE_SENSITIVE="true"

DISABLE_AUTO_TITLE="true"

COMPLETION_WAITING_DOTS="true"

# User configuration
alias ls="ls -lF"

export EDITOR="nvim"
export VISUAL=$EDITOR

export TERM="xterm-256color"

setopt interactivecomments

export PATH="$PATH:/usr/local/bin:/bin:/usr/sbin:/sbin:/usr/bin:$HOME/.local/bin:$HOME/.cargo/bin"

